### ISSUE TITLE
MSSQL

### ISSUE THREAD

**Issue by Japeth** [kubernauts/jmeter-operator#2]
How would one go about connecting this to a MSSQL server instance? (Azure SQL specifically)

**Comment by infinitydon** [comment]
Are you trying to load test an MSSQL server instance? 

If yes, then you can always configure this inside your Jmeter test script, you will have to specify the full address of the MSSQL endpoint. 

![image](https://user-images.githubusercontent.com/6318992/55276387-90b7b580-52f3-11e9-932f-2c5b7057f82e.png)


You only have to ensure that there is a proper network connection between the kubernetes cluster and the MSSQL server instance.

**Comment by Japeth** [comment]
I was more thinking of storing all the data in an Azure SQL server vs an InfluxDB in a pod.

However, the normal BULK INSERT statement doesn't work with Azure SQL, which would force me to use the BCP utility.  This was more work than I wanted, so I just stuck with InfluxDB in a pod with persistent storage.

**Comment by arashkaffamanesh** [comment]
Nice!
