### ISSUE TITLE
How to shut down?

### ISSUE THREAD

**Issue by hyder** [kubernauts/jmeter-operator#7]
Following the guide works fine. But when I try to run my own test plan, I get the following:

Engine is busy - please try later                                                                                                                                      Engine is busy - please try later                                                                                                                                      Engine is busy - please try later                                                                                                                                      Engine is busy - please try later                                                                                                                                      Engine is busy - please try later                                                                                                                                      Remote engines have been started                                                                                                                                       Waiting for possible Shutdown/StopTestNow/Heapdump message on port 4445

How do I shutdown a test?

**Comment by infinitydon** [comment]
You can try by doing a kubectl exec into the master pod (in another shell) and use the following command:

**_/jmeter/apache-jmeter-5.0/bin/stoptest.sh_**

**Comment by hyder** [comment]
Thanks!

**Comment by rupesh2310** [comment]
You can try by doing a kubectl exec into the master pod (in another shell) and use the following command:
/jmeter/apache-jmeter-5.0/bin/stoptest.sh

above command is run properly but for the next test facing same error again

Starting the test @ Thu Jan 05 06:40:50 UTC 2023 (1672900850822)
Engine is busy - please try later
Remote engines have been started
Waiting for possible Shutdown/StopTestNow/Heapdump message on port 4445

how to fix?

**Comment by manitgupta** [comment]
This happens when the slave pods are still executing a test from the previous command. You need to restart the JMeter server in the slaves for them to start accepting requests from the master
