### ISSUE TITLE
error: the path "deploy/crds/loadtest_v1alpha1_jmeter_crd.yaml" does not exist

### ISSUE THREAD

**Issue by Kapish1122** [kubernauts/jmeter-operator#8]
Hi,
So i followed the steps and i am running this in my local virtualbox. I see that the cluster was running and my pod is running as well ( i exposed the service and was able to get the URL as well). When i follow the steps after cloning it in my terminal i am getting the above error. Can you help me fix this issue?

s-MacBook-Air:~ $ git clone https://github.com/kubernauts/jmeter-operator.git
Cloning into 'jmeter-operator'...
remote: Enumerating objects: 145, done.
remote: Counting objects: 100% (145/145), done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 145 (delta 53), reused 124 (delta 38), pack-reused 0
Receiving objects: 100% (145/145), 108.10 KiB | 1.69 MiB/s, done.
Resolving deltas: 100% (53/53), done.
s-MacBook-Air:~ $ kubectl apply -f deploy/crds/loadtest_v1alpha1_jmeter_crd.yaml
error: the path "deploy/crds/loadtest_v1alpha1_jmeter_crd.yaml" does not exist
s-MacBook-Air:~ $ kubectl get crd
No resources found.

**Comment by infinitydon** [comment]
Hi,

You have to be in inside the "jmeter-operator" folder before running the kubectl apply..
```
cd jmeter-operator
```

Then 
```
kubectl apply -f deploy/crds/loadtest_v1alpha1_jmeter_crd.yaml
```

**Comment by Kapish1122** [comment]
Thanks @infinitydon . That fixed my issue.
