### ISSUE TITLE
Grafana link not working

### ISSUE THREAD

**Issue by Kapish1122** [kubernauts/jmeter-operator#9]
HI,
So looks like all the steps are working for me. I wanted to know which ip/link should i use for accessing Grafana. Also, i have minkube installed but i want the grafana to be accessible to any user who wants to run a test. It would be great if you could answer these questions for me. Really appreciate your help. Thanks!!

1. My assumption is that every user who wants to run a test should clone the repo and add the test script in there? Is that correct?
2. Currently i have done this entire setup on my local with minikube but the same can be replicated with kubernetes running on the cloud?
3. Grafana link for jmeter service is accessible to all users or any kind of set up needs to be done for any user? The idea is to get the cluster running and folks can just come in and execute the test by starting the ./start_test.sh (once i have initialized the cluster then they should not have to repeat this).

Lastly, my original question regarding the grafana link. Below is the output . Could you guide me as to how i can access grafana via the jmeter service?

s-MacBook-Air:jmeter-operator $ ./initialize_cluster.sh
Enter the Jmeter Namespace: tqa
Creating Influxdb jmeter Database
Creating the Influxdb data source
{"datasource":{"id":1,"orgId":1,"name":"jmeterdb","type":"influxdb","typeLogoUrl":"","access":"proxy","url":"http://tqa-loadtest-influxdb:8086","password":"admin","user":"admin","database":"jmeter","basicAuth":false,"basicAuthUser":"","basicAuthPassword":"","withCredentials":false,"isDefault":true,"secureJsonFields":{},"version":1,"readOnly":false},"id":1,"message":"Datasource added","name":"jmeterdb"}s-MacBook-Air:jmeter-operator $ kubectl -n tqa get all
NAME                                              READY   STATUS    RESTARTS   AGE
pod/tqa-loadtest-grafana-7b8db9bdb5-v2rr4         1/1     Running   0          39m
pod/tqa-loadtest-influxdb-745b76b6d6-r6c49        1/1     Running   0          39m
pod/tqa-loadtest-jmeter-master-6cd6d7df46-4mm84   1/1     Running   0          40m
pod/tqa-loadtest-jmeter-slaves-768d8c4dc9-gj9   1/1     Running   0          39m
pod/tqa-loadtest-jmeter-slaves-768d8c4dc9-pbnhl   1/1     Running   0          39m

NAME                                     TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
service/tqa-loadtest-grafana             LoadBalancer   10.102.185.69   <pending>     3000:31762/TCP               39m
service/tqa-loadtest-influxdb            ClusterIP      10.96.154.198   <none>        8083/TCP,8086/TCP,2003/TCP   39m
service/tqa-loadtest-jmeter-slaves-svc   ClusterIP      None            <none>        1099/TCP,50000/TCP           39m

NAME                                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/tqa-loadtest-grafana         1/1     1            1           39m
deployment.apps/tqa-loadtest-influxdb        1/1     1            1           39m
deployment.apps/tqa-loadtest-jmeter-master   1/1     1            1           40m
deployment.apps/tqa-loadtest-jmeter-slaves   2/2     2            2           39m

NAME                                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/tqa-loadtest-grafana-7b8db9bdb5         1         1         1       39m
replicaset.apps/tqa-loadtest-influxdb-745b76b6d6        1         1         1       39m
replicaset.apps/tqa-loadtest-jmeter-master-6cd6d7df46   1         1         1       40m
replicaset.apps/tqa-loadtest-jmeter-slaves-768d8c4dc9   2

**Comment by Kapish1122** [comment]
Hi,
Any update on the same? I re tried the entire process but seems like the grafana peice is not working. Any ideas to troubleshoot would help. Thanks!!

**Comment by infinitydon** [comment]
Hi,

1.) You can't access the grafana via the jmeter-service, they are separate things. Grafana has it's own service, the default service type for the Grafana is NodePort, so you should be able to connect to it using the minikube VM physical IP but I noticed you are using a Load balancer service type, minikube has a special way of accessing your application within a kubernetes cluster, I suggest that you check the minikube documentation [minikube_service_doc](https://kubernetes.io/docs/tutorials/hello-minikube/#create-a-service) on how to properly expose your service. Alternatively you should be able to use kubectl forwarding or proxy.

2.) The jmeter-operator can be deployed on any public cloud, with this you will be able to use a globally available load balancer to access your application. Don't forget to secure your services when you expose them to the internet. You can make use of an ingress controller with SSL certificates and authentication, but this is beyond the scope of this project (exposing services can be done several ways, this is left to the end user).

3.) Having multiple teams to carry out tests requires some planning. Note that you can't carry out simultaneous tests. I suggest that each team should create their jmeter deployment in a separate namespace or they do tests in turns. This is entirely up to you.

**Comment by Kapish1122** [comment]
HI,
Thank you for your response. So i did check the minikube doc and followed the steps but the grafana dashboard is still not working for me. I think i am missing a step here. Below is the output for the same. I tried accessing via the browser both the nodeport IP and minkube ip but dont see it working. Meanwhile i am trying the kubectl port forward and hoping that works.

Kapishs-MacBook-Air:jmeter-operator kapishjoshi$ kubectl get services
NAME             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
hello-minikube   NodePort    10.105.193.221   <none>        8080:31995/TCP   25m
kubernetes       ClusterIP   10.96.0.1        <none>        443/TCP          40m
Kapishs-MacBook-Air:jmeter-operator kapishjoshi$ minikube ip
192.168.99.105
s-MacBook-Air:jmeter-operator kapishjoshi$ kubectl expose deployment hello-minikube --type=LoadBalancer --port=8080
Error from server (AlreadyExists): services "hello-minikube" already exists
s-MacBook-Air:jmeter-operator kapishjoshi$ minikube service hello-minikube
🎉  Opening kubernetes service default/hello-minikube in default browser...
-MacBook-Air:jmeter-operator kapishjoshi$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by Kapish1122** [comment]
HI,
I was able to fix the problem and was able to see the dashboard. Hope this helps folks who face a similar issue. Thanks @infinitydon for your help on this.

Solution:
After the above setup is done and all your pods are up and running do the following:
minikube addons list (check if heapster is enabled) if not then run below
minikube addons enable heapster
minikube service list (you should see heapster enabled in this list now)
Access the grafana dashabord via the minikube ip (http://{MINIKUBE-IP}:30002)  - this will be showed when you run minikube service list

**Comment by infinitydon** [comment]
FYI -- I will also like you to note that minikube has some specific ways of administering a kubernetes cluster which is not applicable to a normal kubernetes deployment, just keep that in mind :)

**Comment by Kapish1122** [comment]
ok thanks i will keep that in mind. The jmeter-operator folder is the only thing that needs to be deployed on the public cloud with the test script right? no need to clone the repo for each user correct?

**Comment by infinitydon** [comment]
Yes.. No need to clone the repo for each user, the test script is just a way to test that your jmeter installation works.

Each user/department should create it's own separate namespace and use that namespace (just like tqa) to create their own set of jmeter instance like below:
```
apiVersion: loadtest.jmeter.com/v1alpha1
kind: Jmeter
metadata:
  name: tqa-loadtest
  namespace: tqa
spec:
  # Add fields here
  slave_size: 2
  jmeter_master_image: kubernautslabs/jmeter_master:latest
  jmeter_slave_image: kubernautslabs/jmeter_slave:latest
  grafana_server_root: /
  grafana_service_type: LoadBalancer
  grafana_image: grafana/grafana:5.2.0
  influxdb_image: influxdb
  grafana_install: "true"
  grafana_reporter_install: "false"
  grafana_reporter_image: kubernautslabs/jmeter-reporter:latest
  influxdb_install: "true"
```
